name: Sistema Actividades

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install gspread oauth2client pandas pywhatkit

      - name: Ejecutar sistema
        run: |
          python sistema_principal.py
